### PR TITLE
Ignore falsy keys as they are not compatible with levelup

### PR DESCRIPTION
**Pull request by atamon**
Topics containing messages with empty keys are a bad thing. But once they are there I'd argue it's easier to filter them than re-writing the topic.

### CODE REVIEW

**Comment by solsson** [comment]
I'd like a prometheus counter to increase for every ignored message, possibly labelled by cause

**Comment by atamon** [comment]
My idea was that we'd parse the service log and increase counters in a log processing state. But your solution is of course much better.

@solsson Maybe kafka-cache should export a prometheus metrics interface itself? `KafkaCache.metrics()` or something?

**Comment by solsson** [comment]
> My idea was that we'd parse the service log and increase counters in a log processing state. But your solution is of course much better.

Both are good, but I think log parsing requires unit tests to be trustworthy. Clearly doable.

> @solsson Maybe kafka-cache should export a prometheus metrics interface itself? KafkaCache.metrics() or something?

What is the relation between producing metrics and exposing them? In the java lib it looked like any library can depend on the core API to produce metrics, while the app itself choses a way to expose them.

**Comment by atamon** [comment]
We use siimon/prom-client in nodejs land. And I think the closest similar concept I can find there is `registry`, briefly explained in: https://github.com/siimon/prom-client#multiple-registries. 

The problem in node however is that you can never be sure that you get the same instance of a dependency in another dependency. So even if both kafka-cache and your app use the "global registry" from prom-client, you might get two different instances of this global registry. Looking at https://github.com/siimon/prom-client/blob/master/lib/registry.js#L128 it seems like there's no usage of the actual global scope `global` in there. 

So: Either kafka-cache recognizes an input option for a full instance of prom-client or just a registry, or it exposes its prom-client instances or just its registry. Not sure what's better here.

**Pull request merged**
